name: Build & deploy frontend demo

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |  
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END
      - name: Deploy project
        run:
          ssh target "
          cd ~/deployments/university-frontend
          git pull origin main
          npm install
          npx @chakra-ui/cli snippet add
          npx @chakra-ui/cli snippet add password-input prose
          npm run build
          cp build/ /var/www/university-frontend/ -r
          "


